config/routes.rb
Rails.application.routes.draw do
  resources :doctors do
    resources :appointments
  end

  resources :appointments

  resources :patients

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#destroy'
  # get 'authorized', to: 'sessions#require_login'

  root 'home#about'
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id              :bigint           not null, primary key
#  email           :string
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
  validates :name, presence:true, uniqueness: true

  has_secure_password
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # skip_before_action :authorized, only: [:new, :create]
  before_action :patient, only: %i[show destroy]

  def show
    if @current_patient = @patient
      @appointments = Appointment.this_week.where("patient_id = ?", @current_patient.id)
      respond_to do |format|
        format.html { render 'show.html' }
        format.json { render json: @patient}
      end
    else
      if @current_doctor
        redirect_to doctor_path(@current_doctor)
      elsif @current_patient
        redirect_to patient_path(@current_patient)
      else
        redirect_to root_path
      end
    end
  end

  def new
    redirect
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @current_patient
      flash[:alert] = "This account exits."
      redirect_to patient_path(@current_patient)
    elsif @current_doctor
      flash[:alert] = "You are not allowed to create a patient account."
      redirect_to patient_path(@patient)
    end
    if @patient.save
      login_patient(@patient)
      flash[:notice] = "Successfully signed up."
      redirect_to patient_path(@patient)
    else
      flash.now[:alert] = "Signup failed. Patient account couldn't be created."
      render :new
    end
  end

  def destroy
    if @current_patient
      if @current_patient == @patient
        @patient.destroy
        reset_session
        flash[:notice] = "Successfully deleted your account."
        redirect_to :root
      else
        flash[:alert] = "You are not allowed to delete another Patients account."
      end
    else
      flash[:alert] = "You are not allowed to delete a Patient."
    end
  end

  private
  def patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :email, :password)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= f.label :name %>
<br>
<%= f.text_field :name %>
<br>
<% if patient.errors[:name].any? %>
<p><%= patient.errors.full_messages_for(:name)[0] %>.</p>
<br>
<% end %>

<%= f.label :email, required: true, placeholder: "Patient's email" %>
<br>
<%= f.email_field :email %>
<br>
<% if patient.errors[:email].any? %>
<p><%= patient.errors.full_messages_for(:email)[0] %>.</p>
<br>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit your personal details</h1>
<%= form_for @patient do |f| %>

<%= render :partial => "form", :locals => { :patient => @patient, :f => f} %>

<%= f.button "Update patient", data: { confirm: 'Are you sure you want to save changes to your details?'}%>
<% end %>
<div>
<%= link_to "Cancel", patient_path(@patient), data: { confirm: 'Are you sure you want to discard any changes?'} %>
</div>

app/views/patients/new.html.erb
<h1>Add Patient</h1>
<%= form_for @patient do |f| %>

<%= render :partial => "form", :locals => { :patient => @patient, :f => f} %>

<%= f.label :password %>
<br>
<%= f.password_field :password %>
<br>
<% if @patient.errors[:password].any? %>
<p><%= @patient.errors.full_messages_for(:password)[0] %>.</p>
<br>
<% end %>

<%= f.button "Signup"%>
<% end %>
<div>
<%= link_to "Back", root_path, data: { confirm: 'Are you sure you want to cancel account creation?'}%>
</div>

app/views/patients/show.html.erb
<% if @patient == current_patient %>
<h1>Your Details</h1>
<% else %>
<h1>Patient View</h1>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <td><%= @patient.name %> </td>
  </tr>
  <tr>
    <th>Email</th>
    <td> <%= @patient.email %></td>
  </tr>
</table>

<div>
  <% if @patient.appointments %>
  <%= link_to "View appointments", patient_appointments_path(@patient) %>
  <% end %>
</div>
<% if @patient == @current_patient %>
<div>
  <%= link_to "Edit Patient Details", edit_patient_path %>
</div>
<div>
  <%= button_to "Delete your account", patient_path(@patient), method: :delete, data: { confirm: 'Are you sure you want to delete your account?'} %>
</div>
<% end %>

<% if @patient.doctors.any? %>
  <h2>Your Doctors</h2>
  <hr>
  <div id="patient-doctors-section"></div>
<% end %>

<div class='space-bottom-div'>
</div>
<% if @current_patient = @patient %>
<%= javascript_include_tag 'patients' %>
<%= javascript_include_tag 'doctors' %>
<% end %>