config/routes.rb
Rails.application.routes.draw do
  resources :doctors do
    resources :appointments
  end

  resources :appointments

  resources :patients

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#destroy'
  # get 'authorized', to: 'sessions#require_login'

  root 'home#about'
end

app/models/doctor.rb
# == Schema Information
#
# Table name: doctors
#
#  id              :bigint           not null, primary key
#  address         :string
#  city            :string
#  email           :string
#  name            :string
#  password_digest :string
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  validates :name, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # skip_before_action :authorized, only: [:new, :create]

  def index
    @doctors = Doctor.all
    respond_to do |format|
      format.html { render 'index.html' }
      format.json { render json: @doctors}
    end
  end

  def new
    if @current_doctor
      flash[:alert] = "You already have an account."
      redirect_to doctor_path(@current_doctor)
    elsif @current_patient
      flash[:alert] = "You are not allowed to create a Doctor account."
      redirect_to patient_path(@current_patient)
    end
    @doctor = Doctor.new
  end

  def show
    if @current_doctor
      @all_appointments = @current_doctor.appointments
      @appointments = Appointment.today.where("doctor_id = ?", current_doctor.id)
      @appointment = Appointment.new
      respond_to do |format|
        format.html { render 'show.html' }
        format.json { render json: @all_appointments}
      end
    else
      @appointments = nil
    end
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @current_doctor
      flash[:alert] = "You already have an account."
      redirect_to doctor_path(@current_doctor)
    elsif @current_patient
      flash[:alert] = "You can't create a Doctor account."
      redirect_to patient_path(patient)
    end

    if @doctor.save
      login_doctor(@doctor)
      flash[:notice] = "You have successfully signed up."
      redirect_to doctor_path(@doctor)
    else
      flash.now[:alert] = "Signup failed."
      render :new
    end
  end

  def destroy
    if @current_doctor
      if @current_doctor == @doctor
        @doctor.destroy
        reset_session
        flash[:notice] = "Acount successfully deleted."
        redirect_to root_path
      else
        flash[:alert] = "You are not allowed to delete another Doctors account."
      end
    else
      flash[:alert] = "You are not allowed to delete a Doctor."
    end
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :email, :title, :city, :address, :password)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= f.label :name %>
<br>
<%= f.text_field :name %>
<br>

<%= f.label :title, "Title" %>
<br>
<%= f.text_field :title %>
<br>

<%= f.label :address, "Practice Address (Optional)" %>
<br>
<%= f.text_field :address %>
<br>

<%= f.label :city, "city" %>
<br>
<%= f.city :city %>
<br>

<%= f.label :email %>
<br>
<%= f.email_field :email %>
<br>

app/views/doctors/_view.html.erb
<table data-id="<%= d.id %>">
  <tr>
    <th>Name</th>
    <td><%= d.name %></td>
  </tr>
  <tr>
    <th>Title</th>
    <td><%= d.title %></td>
  </tr>
  <tr>
    <th>Specialty</th>
    <td><%= d.specialty %></td>
  </tr>
  <tr>
    <th>Practice Name</th>
    <td><%= d.practice_name %></td>
  </tr>
  <tr>
    <th>City</th>
    <td ><%= d.city %></td>
  </tr>
</table>

app/views/doctors/edit.html.erb
<h1>Edit Your Personal Details</h1>
<%= form_for @doctor do |f| %>

<%= render :partial => "form", :locals => { :doctor => @doctor, :f => f} %>



<%= f.button "Update Doctor Details", data: { confirm: 'Are you sure you want to save changes to your details?'}%>
<% end %>

<div>
  <%= link_to "Cancel", doctor_path(@doctor), data: { confirm: 'Are you sure you want to discard any changes to your details?'} %>
</div>

app/views/doctors/index.html.erb
<h1>All Doctors</h1>

<% @doctors.each do |d| %>

<%= render :partial => "view", :locals => { :d => d} %>

<div>
  <%=link_to "View Full Details", doctor_path(d) %>
</div>
<hr>
<% end %>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<%= form_for @doctor do |f| %>

<%= render :partial => "form", :locals => { :doctor => @doctor, :f => f} %>

<%= f.label :password %>
<br>
<%= f.password_field :password %>
<br>

<%= f.button "Signup"%>
<% end %>
<div class="margin-top-div">

  <%= link_to "Back", root_path, data: { confirm: 'Are you sure you want to cancel account creation?'}%>
</div>

<div>
</div>

app/views/doctors/show.html.erb
<% if @doctor == current_doctor %>
  <h1>Your Details</h1>
<% else %>
  <h1>Doctor View</h1>
<% end %>

<%= render :partial => "view", :locals => { :d => @doctor} %>

<% if @doctor == current_doctor %>
  <div>
    <%= link_to "View Appointments", doctor_appointments_path(@doctor), :class => "show-page-button" %>
  </div>

  <div>
    <%= link_to "New Appointment", new_doctor_appointment_path(@doctor), :class => "show-page-button" %>
  </div>
<% end %>

<div>
  <%= link_to "View All Doctors", doctors_path, :class => "show-page-button"%>
</div>

<% if @doctor == current_doctor %>
  <div>
    <%= link_to "Edit Doctor Details", edit_doctor_path, :class => "show-page-button" %>
  </div>
  <div>
    <%= button_to "Delete Your Account", doctor_path(@doctor), method: :delete, data: { confirm: 'Are you sure you want to delete your account?'}, :class => "show-page-button" %>
  </div>
<% end %>

<div>

  <% if @doctor == current_doctor && @appointments.any? %>
    <h2>Today's Appointments</h2>
    <% elsif @doctor == current_doctor %>
      <h2>You Have No Appointments Today</h2>
    <% end %>

  <hr>

  <% if @doctor == current_doctor%>
    <h2>Quick Create Appointment</h2>
    <%= form_for @appointment, :html => {:id => "quick-create-form"} do |f| %>
    <%= f.label :date %>
    <br>
    <%= f.date_field :date, value: @appointment.date %>
    <br>

    <%= f.label :time %>
    <br>
    <%= f.time_field :time, value: "%r", value: @appointment.time %>
    <br>
    <% if @appointment.errors[:time].any? %>
      <p><%= @appointment.errors.full_messages_for(:time)[0] %>.</p>
      <br>
    <% end %>
    <%= f.hidden_field :doctor_id, :value => current_doctor.id %>
    <%= f.label(:patient_id, "Patient") %>
    <br>
    <%= f.collection_select(:patient_id, Patient.all.order('name ASC'), :id, :name, include_blank: "Select a patient") %>
    <br>
    <%= f.button "Create Appointment"%>
  <% end %>
<% end %>

<div class='space-bottom-div'></div>