config/routes.rb
Rails.application.routes.draw do
  resources :doctors do
    resources :appointments
  end

  resources :appointments

  resources :patients

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#destroy'
  # get 'authorized', to: 'sessions#require_login'

  root 'home#about'
end

app/models/appointment.rb
# == Schema Information
#
# Table name: appointments
#
#  id         :bigint           not null, primary key
#  date       :string
#  day        :string
#  location   :string
#  reason     :string
#  time       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  doctor_id  :bigint           not null
#  patient_id :bigint           not null
#
# Indexes
#
#  index_appointments_on_doctor_id   (doctor_id)
#  index_appointments_on_patient_id  (patient_id)
#
# Foreign Keys
#
#  fk_rails_...  (doctor_id => doctors.id)
#  fk_rails_...  (patient_id => patients.id)
#
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  scope :today, -> {where(date: Date.today)}
  scope :this_week, -> {where("date >= ? AND date <= ?", Date.today, Date.today+1.week )}

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :appointment, only: %i[show destroy]

  include ActionView::Helpers::UrlHelper

  # GET /appointments
  def index
    # @appointments = Appointment.all
    if @current_patient
      @appointments = @current_patient.appointments
    elsif @current_doctor
      @appointments = @current_doctor.appointments
      respond_to do |format|
        format.html { render 'index.html' }
        format.json { render json: @appointments.today }
      end
    else
      flash[:alert] = "Log in first to view appointments"
      redirect_to root_path
    end
  end

  def show
    if @current_patient
      unless @current_patient == @appointment.patient
        flash[:alert] = "You are not allowed to view this appointment."
        redirect_to appointments_path
      end
    elsif @current_doctor
      unless @current_doctor == @appointment.doctor
        flash[:alert] = "You are not allowed to view this appointment."
        redirect_to appointments_path
      end
    else
      flash[:alert] = "You can't view appointments because you aren't logged in."
      redirect_to root_path
    end
  end

  def new
    @appointment = Appointment.new
  end

  def edit
    if @current_doctor
      unless @current_doctor == @appointment.doctor
        flash[:alert] = "You are not allowed to edit this appointment."
        redirect_to appointments_path
      end
    elsif @current_patient
      unless @curent_patient == @appointment.patient
        flash[:alert] = "You are not allowed to edit appointment."
        redirect_to appointments_path
      end
    end
  end

   # POST /appointments
  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      flash[:notice] = 'Appointment sucessfully created'
      redirect_to appointment_path(@appointment)
    else
      flash.now[:alert] = 'Appointment creation not successful'
      render :new
    end
  end

  # PUT /appointments/1
  def update
    # @appointment = Appointment.update_attribute(params[:id])
    # @appointment.update_attributes(:user_id => current_user.id)
    # if @appointment.save
    #   flash[:notice] = 'Update confirmed!'
    #   redirect_to doctor_appointments_path
    # else
    #   render :new
    # end
  end

  def destroy
    if @current_doctor || @curent_patient
      if @current_doctor == @appointment.doctor || @current_patient == @ppointment.patient
        @appointment.destroy
        flash[:notice] = 'Your appointment has been cancelled successfully '
        redirect_to appointments_path
      else
        flash[:alert] = 'You are not allowed to cancel this appointment.'
        redirect_to appointments_path
      end
    end
  end

  private

  def appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:patient_id, :date, :time, :doctor_id, :reason )
  end
end

app/views/appointments/_form.html.erb
<%= f.label :date %>
<br>
<%= f.date_field :date, value: appointment.date %>
<br>

<%= f.label :time %>
<br>
<%= f.time_field :time, value: "%r", value: appointment.time %>
<br>

<%= f.label :reason %>
<br>
<%= f.text_area :reason %>
<br>

<%= f.label(:doctor_id, "Doctor") %>
<br>
<p><%= current_doctor.name %></p>
<%= f.hidden_field :doctor_id, :value => current_doctor.id %>
<br>

<%= f.label(:patient_id, "Patient") %>
<br>
<%= f.collection_select(:patient_id, Patient.all.order('name ASC'), :id, :name, include_blank: "Select a patient") %>
<br>
  <br>
<% end %>

app/views/appointments/_view.html.erb
<table>
  <tr>
    <th>Date</th>
    <td><%= a.date %></td>
  </tr>

  <tr>
    <th>Time</th>
    <td><%= a.time %></td>
  </tr>

  <% if current_page?(appointment_path(a)) %>
  <tr>
    <th>Patient</th>
    <td><%= link_to a.patient.name, patient_path(a.patient) %></td>
  </tr>

  <tr>
    <th>Doctor</th>
    <td><%= link_to a.doctor.name, doctor_path(a.doctor) %></td>
  </tr>
  <% elsif current_page?(doctor_path(a.doctor)) %>
  <tr>
    <th>Patient</th>
    <td><%= link_to a.patient.name, patient_path(a.patient) %></td>
  </tr>
  <% elsif current_page?(patient_path(a.patient)) %>
  <tr>
    <th>Doctor</th>
    <td><%= link_to a.doctor.name, doctor_path(a.doctor) %></td>
  </tr>
  <% else %>
  <tr>
    <th>Doctor</th>
    <td><%= link_to a.doctor.name, doctor_path(a.doctor) %></td>
  </tr>

  <tr>
    <th>Patient</th>
    <td><%= link_to a.patient.name, patient_path(a.patient) %></td>
  </tr>
  <% end %>

  <tr>
    <th>Reason</th>
    <td><%= a.reason %></td>
  </tr>
</table>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>

<%= form_for @appointment do |f| %>

<%= render :partial => "form", :locals => { :appointment => @appointment, :f => f } %>

<%= f.button "Update Appointment", data: { confirm: 'Are you sure you want to save changes to this appointment?'}%>
<% end %>

<div>
<%= link_to "Cancel", appointment_path(@appointment), data: { confirm: 'Are you sure you want to discard any changes?'}, :class => "show-page-button"%>
</div>

app/views/appointments/index.html.erb
<h1>All your Appointments</h1>
<%= link_to "Add a new appointment", new_appointment_path %>

<hr>
<% @appointments.each do |a| %>

<%= render :partial => "view", :locals => { :a => a} %>

<% end %>

<% if !@appointments.any? %>
  <p>You have no appointments.</p>
<% end %>
<div >
</div>

app/views/appointments/new.html.erb
<h1>New Doctor Appointment</h1>

<%= form_for @appointment do |f| %>

<%= render :partial => "form", :locals => { :appointment => @appointment, :f => f } %>

<%= f.button "Book Appointment"%>
<% end %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<h1>Appointment</h1>

<%= render :partial => "view", :locals => { :a => @appointment} %>

<div>
<%= link_to "View all Appointments", appointments_path, :class => "show-page-button" %>
</div>
<div>
<%= link_to "Edit Appointment", edit_appointment_path(@appointment)%>
</div>
<div>
<%= button_to "Delete Appointment", appointment_path(@appointment), method: "delete", data: { confirm: 'Are you sure you want to delete this appointment?'}%>
</div>